### ISSUE TITLE
So how to build it?

### ISSUE THREAD

**Issue by olgierd-on-fire** [marcojakob/code.makery.ch#121]
I've read README.md but yet I don't understand and what do I need to translate?

**Comment by marcojakob** [comment]
If you want to contribute to translations you can follow this guide: http://code.makery.ch/library/how-to-contribute/

The README is only about how you would build the website if you wanted to clone it completely. Unfortunately, mixture.io - the static website builder - has been discontinued. At some point we will have to move to some other website builder. My current favorite is [hugo](gohugo.io)

**Comment by olgierd-on-fire** [comment]
@marcojakob Unfortunately, your link has broken. This is it: [hugo](https://github.com/spf13/hugo)
