### ISSUE TITLE
Migrate to Hugo

### ISSUE THREAD

**Issue by marcojakob** [marcojakob/code.makery.ch#132]
Since the currently used Static Site Generator (mixture.io) has been discontinued long ago, we have to switch to another generator. We plan to migrate to [Hugo](https://gohugo.io/). It's not a trivial task with all the languages and complex structure of tutorials and tutorial parts.

**Comment by jeffge2017** [comment]
The URL of the following text needs to be updated:

What's Next?
In Tutorial Part 3 we will add more functionality like adding, deleting and editing Persons.

Present URL: /library/javafx-8-tutorial/part3
Correct URL: javafx-8-tutorial-en-part3.md
