### ISSUE TITLE
http://code.makery.ch is down?

### ISSUE THREAD

**Issue by zxxz** [marcojakob/code.makery.ch#94]
Hello,
http://code.makery.ch is down.
Any idea when it will be up again?

**Comment by marcojakob** [comment]
Thanks for telling me. I made a stupid mistake... Will be back up in a few seconds.

**Comment by zxxz** [comment]
It's all good now, thanks! :-)
With the weekend ahead I will now be able to complete your awesome JavaFX 8 Tutorial ;-)
